In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = {
    "Date": [
        "2026-10-01", "2026-10-01", "2026-10-02", "2026-10-02",
        "2026-10-03", "2026-10-03", "2026-10-04", "2026-10-04",
        "2026-10-05", "2026-10-05", "2026-10-06", "2026-10-06",
        "2026-10-06"
    ],
    "Product": [
        "Laptop", "Mouse", "Keyboard", "Monitor",
        "Laptop", "Mouse", "Keyboard", "Monitor",
        "Laptop", "Mouse", "Keyboard", "Monitor",
        "Monitor"
    ],
    "Category": [
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics"
    ],
    "Region": [
        "Chennai", "Bengaluru", "Chennai", "Hyderabad",
        "Bengaluru", "Hyderabad", "Chennai", "Bengaluru",
        "Hyderabad", "Chennai", "Bengaluru", "Hyderabad",
        "Hyderabad"
    ],
    "Price": [
        50000, 500, 1500, 12000,
        50000, 500, 1500, 12000,
        50000, 500, np.nan, 12000,
        12000
    ],
    "Quantity": [
        2, 10, 5, 2,
        1, 8, 4, 3,
        2, 12, 6, np.nan,
        np.nan
    ],
    "Cost_Per_Unit": [
        40000, 300, 1000, 9000,
        40000, 300, 1000, 9000,
        40000, 300, 1000, 9000,
        9000
    ],
    "Discount": [
        2000, 100, 200, 1000,
        1000, 50, 100, 500,
        2000, 100, 200, 500,
        500
    ]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
df["Date"] = pd.to_datetime(df["Date"])

In [6]:
display(df)

,Date,Product,Category,Region,Price,Quantity,Cost_Per_Unit,Discount
0,2026-10-01,Laptop,Electronics,Chennai,50000.0,2.0,40000,2000
1,2026-10-01,Mouse,Accessories,Bengaluru,500.0,10.0,300,100
2,2026-10-02,Keyboard,Accessories,Chennai,1500.0,5.0,1000,200
3,2026-10-02,Monitor,Electronics,Hyderabad,12000.0,2.0,9000,1000
4,2026-10-03,Laptop,Electronics,Bengaluru,50000.0,1.0,40000,1000
5,2026-10-03,Mouse,Accessories,Hyderabad,500.0,8.0,300,50
6,2026-10-04,Keyboard,Accessories,Chennai,1500.0,4.0,1000,100
7,2026-10-04,Monitor,Electronics,Bengaluru,12000.0,3.0,9000,500
8,2026-10-05,Laptop,Electronics,Hyderabad,50000.0,2.0,40000,2000
9,2026-10-05,Mouse,Accessories,Chennai,500.0,12.0,300,100
10,2026-10-06,Keyboard,Accessories,Bengaluru,NaN,6.0,1000,200
11,2026-10-06,Monitor,Electronics,Hyderabad,12000.0,NaN,9000,500
12,2026-10-06,Monitor,Electronics,Hyderabad,12000.0,NaN,9000,500

# Numpy arrays

### creating arrays

In [8]:
prices = df["Price"].to_numpy()
quantities = df["Quantity"].to_numpy()

In [9]:
print("Prices:", prices)
print("Quantities:", quantities)

Prices: [50000.   500.  1500. 12000. 50000.   500.  1500. 12000. 50000.   500.
    nan 12000. 12000.]
Quantities: [ 2. 10.  5.  2.  1.  8.  4.  3.  2. 12.  6. nan nan]

### handling missing values

In [10]:
prices = np.nan_to_num(prices, nan=0)
quantities = np.nan_to_num(quantities, nan=0)

In [12]:
print("Addition:", (prices + quantities).astype(int))

Addition: [50002   510  1505 12002 50001   508  1504 12003 50002   512     6 12000
 12000]

In [14]:
print("Subtraction:", (prices - quantities).astype(int))

Subtraction: [49998   490  1495 11998 49999   492  1496 11997 49998   488    -6 12000
 12000]

In [15]:
print("Multiplication:", (prices * quantities).astype(int))

Multiplication: [100000   5000   7500  24000  50000   4000   6000  36000 100000   6000
      0      0      0]

In [16]:
print("Total prices:", np.sum(prices))

Total prices: 202500.0

In [17]:
print("Average price:", np.mean(prices))

Average price: 15576.923076923076

In [18]:
print("Minimum price:", np.min(prices))

Minimum price: 0.0

In [19]:
print("Maximum price:", np.max(prices))

Maximum price: 50000.0

# Pandas Series

In [21]:
prices = df["Price"]
print(prices)

0     50000.0
1       500.0
2      1500.0
3     12000.0
4     50000.0
5       500.0
6      1500.0
7     12000.0
8     50000.0
9       500.0
10        NaN
11    12000.0
12    12000.0
Name: Price, dtype: float64

In [22]:
print(prices.sum())

202500.0

In [23]:
print(prices.mean())

16875.0

In [24]:
print(prices.min())

500.0

In [25]:
print(prices.max())

50000.0

In [26]:
print(prices.iloc[:3])

0    50000.0
1      500.0
2     1500.0
Name: Price, dtype: float64

prices above 1000

In [27]:
display(df.loc[df["Price"] > 1000, ["Product", "Price"]])

     Product    Price
0     Laptop  50000.0
2   Keyboard   1500.0
3    Monitor  12000.0
4     Laptop  50000.0
6   Keyboard   1500.0
7    Monitor  12000.0
8     Laptop  50000.0
11   Monitor  12000.0
12   Monitor  12000.0

# Creating a new column based off the old ones

In [28]:
df["Revenue"] = df["Price"] * df["Quantity"]

In [29]:
print("Total revenue:", df["Revenue"].sum())
print("Average transaction revenue:", df["Revenue"].mean())

Total revenue: 338500.0
Average transaction revenue: 33850.0

In [30]:
daily_revenue = df.groupby("Date")["Revenue"].sum()
print("Daily revenue:")
display(daily_revenue)

Daily revenue:

Date
2026-10-01    105000.0
2026-10-02     31500.0
2026-10-03     54000.0
2026-10-04     42000.0
2026-10-05    106000.0
2026-10-06         0.0
Name: Revenue, dtype: float64

# Compare NumPy and Pandas on the same revenue values

In [31]:
revenue_values = df["Revenue"].dropna().to_numpy()

In [32]:
print("NumPy total revenue:", np.sum(revenue_values))
print("Pandas total revenue:", df["Revenue"].sum())

NumPy total revenue: 338500.0
Pandas total revenue: 338500.0

# Data Exploration

In [33]:
display(df.head())

,Date,Product,Category,Region,Price,Quantity,Cost_Per_Unit,Discount,Revenue
0,2026-10-01,Laptop,Electronics,Chennai,50000.0,2.0,40000,2000,100000.0
1,2026-10-01,Mouse,Accessories,Bengaluru,500.0,10.0,300,100,5000.0
2,2026-10-02,Keyboard,Accessories,Chennai,1500.0,5.0,1000,200,7500.0
3,2026-10-02,Monitor,Electronics,Hyderabad,12000.0,2.0,9000,1000,24000.0
4,2026-10-03,Laptop,Electronics,Bengaluru,50000.0,1.0,40000,1000,50000.0

In [34]:
display(df.tail())

,Date,Product,Category,Region,Price,Quantity,Cost_Per_Unit,Discount,Revenue
8,2026-10-05,Laptop,Electronics,Hyderabad,50000.0,2.0,40000,2000,100000.0
9,2026-10-05,Mouse,Accessories,Chennai,500.0,12.0,300,100,6000.0
10,2026-10-06,Keyboard,Accessories,Bengaluru,NaN,6.0,1000,200,NaN
11,2026-10-06,Monitor,Electronics,Hyderabad,12000.0,NaN,9000,500,NaN
12,2026-10-06,Monitor,Electronics,Hyderabad,12000.0,NaN,9000,500,NaN

In [35]:
print(df.shape)

(13, 9)

In [37]:
print(df.columns.tolist())

['Date', 'Product', 'Category', 'Region', 'Price', 'Quantity', 'Cost_Per_Unit', 'Discount', 'Revenue']

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           13 non-null     datetime64[ns]
 1   Product        13 non-null     object
 2   Category       13 non-null     object
 3   Region         13 non-null     object
 4   Price          12 non-null     float64
 5   Quantity       11 non-null     float64
 6   Cost_Per_Unit  13 non-null     int64
 7   Discount       13 non-null     int64
 8   Revenue        10 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(3)
memory usage: 1.0+ KB

In [39]:
display(df.describe())

,Date,Price,Quantity,Cost_Per_Unit,Discount,Revenue
count,13,12.000000,11.00000,13.000000,13.000000,10.000000
mean,2026-10-03 16:36:55.384615424,16875.000000,5.00000,12300.000000,634.615385,33850.000000
min,2026-10-01 00:00:00,500.000000,1.00000,300.000000,50.000000,4000.000000
25%,2026-10-02 00:00:00,1250.000000,2.00000,1000.000000,100.000000,6000.000000
50%,2026-10-04 00:00:00,12000.000000,4.00000,9000.000000,500.000000,15750.000000
75%,2026-10-05 00:00:00,21500.000000,7.00000,9000.000000,1000.000000,46500.000000
max,2026-10-06 00:00:00,50000.000000,12.00000,40000.000000,2000.000000,100000.000000
std,NaN,20591.398248,3.63318,16228.832367,684.770222,38127.017251

# Data Cleaning

In [40]:
df_clean = df.drop_duplicates().copy()

### filling missing values

In [41]:
df_clean["Price"] = df_clean["Price"].fillna(df_clean["Price"].median())
df_clean["Quantity"] = df_clean["Quantity"].fillna(df_clean["Quantity"].median())

In [42]:
df_clean["Revenue"] = df_clean["Price"] * df_clean["Quantity"]

In [43]:
df_clean["Total_Cost"] = (
    df_clean["Cost_Per_Unit"] * df_clean["Quantity"]
)

In [44]:
df_clean["Profit"] = (
    df_clean["Revenue"] - df_clean["Discount"] - df_clean["Total_Cost"]
)

In [45]:
df_clean["Profit_Margin_%"] = np.where(
    df_clean["Revenue"] != 0,
    df_clean["Profit"] / df_clean["Revenue"] * 100,
    np.nan
)

In [46]:
display(df_clean)

,Date,Product,Category,Region,Price,Quantity,Cost_Per_Unit,Discount,Revenue,Total_Cost,Profit,Profit_Margin_%
0,2026-10-01,Laptop,Electronics,Chennai,50000.0,2.0,40000,2000,100000.0,80000.0,18000.0,18.000000
1,2026-10-01,Mouse,Accessories,Bengaluru,500.0,10.0,300,100,5000.0,3000.0,1900.0,38.000000
2,2026-10-02,Keyboard,Accessories,Chennai,1500.0,5.0,1000,200,7500.0,5000.0,2300.0,30.666667
3,2026-10-02,Monitor,Electronics,Hyderabad,12000.0,2.0,9000,1000,24000.0,18000.0,5000.0,20.833333
4,2026-10-03,Laptop,Electronics,Bengaluru,50000.0,1.0,40000,1000,50000.0,40000.0,9000.0,18.000000
5,2026-10-03,Mouse,Accessories,Hyderabad,500.0,8.0,300,50,4000.0,2400.0,1550.0,38.750000
6,2026-10-04,Keyboard,Accessories,Chennai,1500.0,4.0,1000,100,6000.0,4000.0,1900.0,31.666667
7,2026-10-04,Monitor,Electronics,Bengaluru,12000.0,3.0,9000,500,36000.0,27000.0,8500.0,23.611111
8,2026-10-05,Laptop,Electronics,Hyderabad,50000.0,2.0,40000,2000,100000.0,80000.0,18000.0,18.000000
9,2026-10-05,Mouse,Accessories,Chennai,500.0,12.0,300,100,6000.0,3600.0,2300.0,38.333333
10,2026-10-06,Keyboard,Accessories,Bengaluru,12000.0,6.0,1000,200,72000.0,6000.0,65800.0,91.388889
11,2026-10-06,Monitor,Electronics,Hyderabad,12000.0,4.0,9000,500,48000.0,36000.0,11500.0,23.958333

In [47]:
print(df_clean.isnull().sum())

Date               0
Product            0
Category           0
Region             0
Price              0
Quantity           0
Cost_Per_Unit      0
Discount           0
Revenue            0
Total_Cost         0
Profit             0
Profit_Margin_%    0
dtype: int64

In [48]:
print("Duplicate rows:", df_clean.duplicated().sum())

Duplicate rows: 0

In [49]:
print("Total revenue:", df_clean["Revenue"].sum())
print("Total profit:", df_clean["Profit"].sum())
print("Average profit margin:", df_clean["Profit_Margin_%"].mean())

Total revenue: 458500.0
Total profit: 145750.0
Average profit margin: 32.60069444444444

# Applying different filters

### 1. Filter by category

In [53]:
print("Electronics transactions:")
display(df_clean[df_clean["Category"] == "Electronics"])

Electronics transactions:

,Date,Product,Category,Region,Price,Quantity,Cost_Per_Unit,Discount,Revenue,Total_Cost,Profit,Profit_Margin_%
0,2026-10-01,Laptop,Electronics,Chennai,50000.0,2.0,40000,2000,100000.0,80000.0,18000.0,18.000000
3,2026-10-02,Monitor,Electronics,Hyderabad,12000.0,2.0,9000,1000,24000.0,18000.0,5000.0,20.833333
4,2026-10-03,Laptop,Electronics,Bengaluru,50000.0,1.0,40000,1000,50000.0,40000.0,9000.0,18.000000
7,2026-10-04,Monitor,Electronics,Bengaluru,12000.0,3.0,9000,500,36000.0,27000.0,8500.0,23.611111
8,2026-10-05,Laptop,Electronics,Hyderabad,50000.0,2.0,40000,2000,100000.0,80000.0,18000.0,18.000000
11,2026-10-06,Monitor,Electronics,Hyderabad,12000.0,4.0,9000,500,48000.0,36000.0,11500.0,23.958333

### 2. Quantity greater than 5

In [54]:
print("Transactions with quantity above 5:")
display(df_clean[df_clean["Quantity"] > 5])

Transactions with quantity above 5:

,Date,Product,Category,Region,Price,Quantity,Cost_Per_Unit,Discount,Revenue,Total_Cost,Profit,Profit_Margin_%
1,2026-10-01,Mouse,Accessories,Bengaluru,500.0,10.0,300,100,5000.0,3000.0,1900.0,38.000000
5,2026-10-03,Mouse,Accessories,Hyderabad,500.0,8.0,300,50,4000.0,2400.0,1550.0,38.750000
9,2026-10-05,Mouse,Accessories,Chennai,500.0,12.0,300,100,6000.0,3600.0,2300.0,38.333333
10,2026-10-06,Keyboard,Accessories,Bengaluru,12000.0,6.0,1000,200,72000.0,6000.0,65800.0,91.388889

### 3. AND condition: Chennai and revenue above 5000

In [55]:
print("Chennai transactions with revenue above 5000:")
display(df_clean[
    (df_clean["Region"] == "Chennai") &
    (df_clean["Revenue"] > 5000)
])

Chennai transactions with revenue above 5000:

,Date,Product,Category,Region,Price,Quantity,Cost_Per_Unit,Discount,Revenue,Total_Cost,Profit,Profit_Margin_%
0,2026-10-01,Laptop,Electronics,Chennai,50000.0,2.0,40000,2000,100000.0,80000.0,18000.0,18.000000
2,2026-10-02,Keyboard,Accessories,Chennai,1500.0,5.0,1000,200,7500.0,5000.0,2300.0,30.666667
6,2026-10-04,Keyboard,Accessories,Chennai,1500.0,4.0,1000,100,6000.0,4000.0,1900.0,31.666667
9,2026-10-05,Mouse,Accessories,Chennai,500.0,12.0,300,100,6000.0,3600.0,2300.0,38.333333

### 4. OR condition: Chennai or Bengaluru

In [56]:
print("Transactions from Chennai or Bengaluru:")
display(df_clean[
    (df_clean["Region"] == "Chennai") |
    (df_clean["Region"] == "Bengaluru")
])

Transactions from Chennai or Bengaluru:

,Date,Product,Category,Region,Price,Quantity,Cost_Per_Unit,Discount,Revenue,Total_Cost,Profit,Profit_Margin_%
0,2026-10-01,Laptop,Electronics,Chennai,50000.0,2.0,40000,2000,100000.0,80000.0,18000.0,18.000000
1,2026-10-01,Mouse,Accessories,Bengaluru,500.0,10.0,300,100,5000.0,3000.0,1900.0,38.000000
2,2026-10-02,Keyboard,Accessories,Chennai,1500.0,5.0,1000,200,7500.0,5000.0,2300.0,30.666667
4,2026-10-03,Laptop,Electronics,Bengaluru,50000.0,1.0,40000,1000,50000.0,40000.0,9000.0,18.000000
6,2026-10-04,Keyboard,Accessories,Chennai,1500.0,4.0,1000,100,6000.0,4000.0,1900.0,31.666667
7,2026-10-04,Monitor,Electronics,Bengaluru,12000.0,3.0,9000,500,36000.0,27000.0,8500.0,23.611111
9,2026-10-05,Mouse,Accessories,Chennai,500.0,12.0,300,100,6000.0,3600.0,2300.0,38.333333
10,2026-10-06,Keyboard,Accessories,Bengaluru,12000.0,6.0,1000,200,72000.0,6000.0,65800.0,91.388889

### 5. Date range: October 2 to October 4

In [57]:
print("Transactions from October 2 to October 4:")
display(df_clean[
    (df_clean["Date"] >= "2026-10-02") &
    (df_clean["Date"] <= "2026-10-04")
])

Transactions from October 2 to October 4:

,Date,Product,Category,Region,Price,Quantity,Cost_Per_Unit,Discount,Revenue,Total_Cost,Profit,Profit_Margin_%
2,2026-10-02,Keyboard,Accessories,Chennai,1500.0,5.0,1000,200,7500.0,5000.0,2300.0,30.666667
3,2026-10-02,Monitor,Electronics,Hyderabad,12000.0,2.0,9000,1000,24000.0,18000.0,5000.0,20.833333
4,2026-10-03,Laptop,Electronics,Bengaluru,50000.0,1.0,40000,1000,50000.0,40000.0,9000.0,18.000000
5,2026-10-03,Mouse,Accessories,Hyderabad,500.0,8.0,300,50,4000.0,2400.0,1550.0,38.750000
6,2026-10-04,Keyboard,Accessories,Chennai,1500.0,4.0,1000,100,6000.0,4000.0,1900.0,31.666667
7,2026-10-04,Monitor,Electronics,Bengaluru,12000.0,3.0,9000,500,36000.0,27000.0,8500.0,23.611111

### 6. Filter by derived column: profit above 5000

In [58]:
print("Transactions with profit above 5000:")
display(df_clean[df_clean["Profit"] > 5000])

Transactions with profit above 5000:

,Date,Product,Category,Region,Price,Quantity,Cost_Per_Unit,Discount,Revenue,Total_Cost,Profit,Profit_Margin_%
0,2026-10-01,Laptop,Electronics,Chennai,50000.0,2.0,40000,2000,100000.0,80000.0,18000.0,18.000000
4,2026-10-03,Laptop,Electronics,Bengaluru,50000.0,1.0,40000,1000,50000.0,40000.0,9000.0,18.000000
7,2026-10-04,Monitor,Electronics,Bengaluru,12000.0,3.0,9000,500,36000.0,27000.0,8500.0,23.611111
8,2026-10-05,Laptop,Electronics,Hyderabad,50000.0,2.0,40000,2000,100000.0,80000.0,18000.0,18.000000
10,2026-10-06,Keyboard,Accessories,Bengaluru,12000.0,6.0,1000,200,72000.0,6000.0,65800.0,91.388889
11,2026-10-06,Monitor,Electronics,Hyderabad,12000.0,4.0,9000,500,48000.0,36000.0,11500.0,23.958333

### 7. NOT condition: exclude Electronics

In [59]:
print("Transactions excluding Electronics:")
display(df_clean[~(df_clean["Category"] == "Electronics")])

Transactions excluding Electronics:

,Date,Product,Category,Region,Price,Quantity,Cost_Per_Unit,Discount,Revenue,Total_Cost,Profit,Profit_Margin_%
1,2026-10-01,Mouse,Accessories,Bengaluru,500.0,10.0,300,100,5000.0,3000.0,1900.0,38.000000
2,2026-10-02,Keyboard,Accessories,Chennai,1500.0,5.0,1000,200,7500.0,5000.0,2300.0,30.666667
5,2026-10-03,Mouse,Accessories,Hyderabad,500.0,8.0,300,50,4000.0,2400.0,1550.0,38.750000
6,2026-10-04,Keyboard,Accessories,Chennai,1500.0,4.0,1000,100,6000.0,4000.0,1900.0,31.666667
9,2026-10-05,Mouse,Accessories,Chennai,500.0,12.0,300,100,6000.0,3600.0,2300.0,38.333333
10,2026-10-06,Keyboard,Accessories,Bengaluru,12000.0,6.0,1000,200,72000.0,6000.0,65800.0,91.388889